version: '3.4'

services:
  postgres.data:
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ConformitDb"
      POSTGRES_USER: "postgres"
    volumes:
      - postgresdata-volume:/var/lib/postgresql/data
    ports:
      - "55432:5432"
      
  testprogrammationconformit:
    environment:
       ASPNETCORE_ENVIRONMENT: "Development"
       ConformitDb: "Host=postgres.data;Port=5432;Database=ConformitDb;Username=postgres;Password=admin"

    ports:
      - "5001:80"
    command: dotnet ef database update
    

volumes:
  postgresdata-volume: